export const CREATE_EVENT = 'CREATE_EVENT';
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS';
export const CREATE_EVENT_FAILED = 'CREATE_EVENT_FAILED';

export const GET_EVENTS = 'GET_EVENTS';
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS';
export const GET_EVENTS_FAILED = 'GET_EVENTS_FAILED';

export const GET_EVENT_BY_ID = 'GET_EVENT_BY_ID';
export const GET_EVENT_BY_ID_SUCCESS = 'GET_EVENT_BY_ID_SUCCESS';
export const GET_EVENT_BY_ID_FAILED = 'GET_EVENT_BY_ID_FAILED';

export const UPDATE_EVENT = 'UPDATE_EVENT';
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS';
export const UPDATE_EVENT_FAILED = 'UPDATE_EVENT_FAILED';

export const DELETE_EVENT = 'DELETE_EVENT';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';
export const DELETE_EVENT_FAILED = 'DELETE_EVENT_FAILED';

export const TYPE_GAMES = 'TYPE_GAMES';
export const TYPE_GAMES_SUCCESS = 'TYPE_GAMES_SUCCESS';
export const TYPE_GAMES_FAILED = 'TYPE_GAMES_FAILED';


export const CREATE_PLAYER = 'CREATE_PLAYER';
export const CREATE_PLAYER_SUCCESS = 'CREATE_PLAYER_SUCCESS';
export const CREATE_PLAYER_FAILED = 'CREATE_PLAYER_FAILED';

export const GET_PLAYERS_BY_ID = 'GET_PLAYERS_BY_ID';
export const GET_PLAYERS_BY_ID_SUCCESS = 'GET_PLAYERS_BY_ID_SUCCESS';
export const GET_PLAYERS_BY_ID_FAILED = 'GET_PLAYERS_BY_ID_FAILED';

export const GET_PLAYER_BY_ID = 'GET_PLAYER_BY_ID';
export const GET_PLAYER_BY_ID_SUCCESS = 'GET_PLAYER_BY_ID_SUCCESS';
export const GET_PLAYER_BY_ID_FAILED = 'GET_PLAYER_BY_ID_FAILED';

export const DELETE_PLAYER = 'DELETE_PLAYER';
export const DELETE_PLAYER_SUCCESS = 'DELETE_PLAYER_SUCCESS';
export const DELETE_PLAYER_FAILED = 'DELETE_PLAYER_FAILED';

export const UPDATE_PLAYER = 'UPDATE_PLAYER';
export const UPDATE_PLAYER_SUCCESS = 'UPDATE_PLAYER_SUCCESS';
export const UPDATE_PLAYER_FAILED = 'UPDATE_PLAYER_FAILED';



